####################################################################

PHOME=..
include $(PHOME)/unix/config.mk

####################################################################

.PHONY: default tidy clean purge

default:
	@ $(ECHO) "targets:\n   tidy\n   clean"

tidy:
	@ $(TIDYDIR)

clean:
	@ $(CLEANDIR)

####################################################################
